behaviors:
  Snake:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      num_epoch: 3
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 3
    time_horizon: 64
    max_steps: 1000000
    summary_freq: 25000
